### ISSUE TITLE
gnome-mpv build fail

### ISSUE THREAD

**Issue by nado** [rilian-la-te/lxde-gtk3-overlay#1]
Hi,

I get stuck trying to build gnome-mpv, here is the output of intltoolize which is the one failing.

[intltoolize.out.txt](https://github.com/rilian-la-te/lxde-gtk3-overlay/files/199450/intltoolize.out.txt)

I confirm that /usr/share/aclocal/intltool.m4 is there.

Here is the build log for better understanding. 
[build.log.txt](https://github.com/rilian-la-te/lxde-gtk3-overlay/files/199455/build.log.txt)

**Comment by nado** [comment]
Since gtk+3-3.20 is not yet in gentoo repos, I will try to make a PR with other fixes when we’ll have gtk+3-3.20 in ~amd64.

**Comment by rilian-la-te** [comment]
When I will have time and good Internet, I will try to fix it.

**Comment by rilian-la-te** [comment]
When I will have time and good Internet, I will try to fix it.
On Apr 1, 2016 5:49 PM, "nado" notifications@github.com wrote:

Since gtk+3-3.20 is not yet in gentoo repos, I will try to make a PR with
other fixes when we’ll have gtk+3-3.20 in ~amd64.
